# Code generated by contracts/codegen.py. DO NOT EDIT.
"""Generated Bronze-layer models (raw collected news)."""

from __future__ import annotations

from dataclasses import dataclass

from econ_core.models.enums import Axis


@dataclass(kw_only=True)
class NewsItem:
    """Bronze record — a raw collected news item preserved with provenance metadata (PRD ingestion, AC1.1-AC1.6)."""

    record_id: str
    source_id: str
    axis: Axis
    rank: int
    view_count: int
    title: str
    source_url: str
    raw_text: str
    body_available: bool
    collected_at: str
    collection_cycle: str

    @classmethod
    def from_dict(cls, d: dict) -> NewsItem:
        return cls(
            record_id=d["record_id"],
            source_id=d["source_id"],
            axis=d["axis"],
            rank=d["rank"],
            view_count=d["view_count"],
            title=d["title"],
            source_url=d["source_url"],
            raw_text=d["raw_text"],
            body_available=d["body_available"],
            collected_at=d["collected_at"],
            collection_cycle=d["collection_cycle"],
        )
