# Code generated by contracts/codegen.py. DO NOT EDIT.
"""Generated Bronze-layer models (raw collected news)."""

from __future__ import annotations

from dataclasses import dataclass

from econ_core.models.enums import Axis


@dataclass(kw_only=True)
class NewsBody:
    """Bronze record — one immutable body version, stored once and content-addressed by SHA-256; unchanged bodies are never re-stored and edited bodies append a new version (PRD ingestion, AC1.4, AC1.7)."""

    body_hash: str
    raw_text: str
    first_seen_at: str
    first_seen_cycle: str

    @classmethod
    def from_dict(cls, d: dict) -> NewsBody:
        return cls(
            body_hash=d["body_hash"],
            raw_text=d["raw_text"],
            first_seen_at=d["first_seen_at"],
            first_seen_cycle=d["first_seen_cycle"],
        )


@dataclass(kw_only=True)
class NewsItem:
    """Bronze record — one collection observation of a news item with provenance metadata; the body itself lives in news_body, referenced by hash (PRD ingestion, AC1.1-AC1.7)."""

    record_id: str
    source_id: str
    axis: Axis
    rank: int
    view_count: int
    title: str
    source_url: str
    body_hash: str
    body_available: bool
    collected_at: str
    collection_cycle: str

    @classmethod
    def from_dict(cls, d: dict) -> NewsItem:
        return cls(
            record_id=d["record_id"],
            source_id=d["source_id"],
            axis=d["axis"],
            rank=d["rank"],
            view_count=d["view_count"],
            title=d["title"],
            source_url=d["source_url"],
            body_hash=d["body_hash"],
            body_available=d["body_available"],
            collected_at=d["collected_at"],
            collection_cycle=d["collection_cycle"],
        )
