# Code generated by contracts/codegen.py. DO NOT EDIT.
"""Generated enum value sets shared across data-lake layers."""

from typing import Literal

AnalysisStatus = Literal["analyzed", "low_confidence", "unanalyzed"]
ANALYSISSTATUS_VALUES: tuple[AnalysisStatus, ...] = ("analyzed", "low_confidence", "unanalyzed")

Axis = Literal["KR", "US", "GLOBAL"]
AXIS_VALUES: tuple[Axis, ...] = ("KR", "US", "GLOBAL")

BucketUnit = Literal["hour", "day", "week"]
BUCKETUNIT_VALUES: tuple[BucketUnit, ...] = ("hour", "day", "week")

Sentiment = Literal["positive", "neutral", "negative", "mixed"]
SENTIMENT_VALUES: tuple[Sentiment, ...] = ("positive", "neutral", "negative", "mixed")
