# Code generated by contracts/codegen.py. DO NOT EDIT.
"""Generated Gold-layer models (normalized aggregation)."""

from __future__ import annotations

from dataclasses import dataclass, field

from econ_core.models.enums import Axis, BucketUnit


@dataclass(kw_only=True)
class AxisSentiment:
    """Gold record — per (axis, time bucket) sentiment distribution (AC5.3, AC5.5)."""

    axis: Axis
    bucket_unit: BucketUnit
    time_bucket: str
    distribution: SentimentDistribution
    analyzed_total: int

    @classmethod
    def from_dict(cls, d: dict) -> AxisSentiment:
        return cls(
            axis=d["axis"],
            bucket_unit=d["bucket_unit"],
            time_bucket=d["time_bucket"],
            distribution=SentimentDistribution.from_dict(d["distribution"]),
            analyzed_total=d["analyzed_total"],
        )


@dataclass(kw_only=True)
class SentimentDistribution:
    """Sentiment ratios for analyzed items; unanalyzed kept separate (AC5.3, AC5.5)."""

    positive: float
    neutral: float
    negative: float
    mixed: float
    unanalyzed: float

    @classmethod
    def from_dict(cls, d: dict) -> SentimentDistribution:
        return cls(
            positive=d["positive"],
            neutral=d["neutral"],
            negative=d["negative"],
            mixed=d["mixed"],
            unanalyzed=d["unanalyzed"],
        )


@dataclass(kw_only=True)
class SubjectSourceContribution:
    """Gold record — how much one collection source contributed to a (subject, axis, time bucket) value (AC6.3). Kept in its own dataset so readers that do not know the source dimension cannot double-count the subject-level rows of SubjectTrend."""

    subject: str
    axis: Axis
    bucket_unit: BucketUnit
    time_bucket: str
    source_id: str
    raw_count: int
    raw_share: float
    normalized_contribution: float

    @classmethod
    def from_dict(cls, d: dict) -> SubjectSourceContribution:
        return cls(
            subject=d["subject"],
            axis=d["axis"],
            bucket_unit=d["bucket_unit"],
            time_bucket=d["time_bucket"],
            source_id=d["source_id"],
            raw_count=d["raw_count"],
            raw_share=d["raw_share"],
            normalized_contribution=d["normalized_contribution"],
        )


@dataclass(kw_only=True)
class SubjectTrend:
    """Gold record — per (subject, axis, time bucket) trend aggregation (AC6.1-AC5.2, AC5.4, AC6.2)."""

    subject: str
    axis: Axis
    bucket_unit: BucketUnit
    time_bucket: str
    raw_count: int
    normalized_share: float
    delta: float
    spark: list[float] = field(default_factory=list)

    @classmethod
    def from_dict(cls, d: dict) -> SubjectTrend:
        return cls(
            subject=d["subject"],
            axis=d["axis"],
            bucket_unit=d["bucket_unit"],
            time_bucket=d["time_bucket"],
            raw_count=d["raw_count"],
            normalized_share=d["normalized_share"],
            delta=d["delta"],
            spark=list(d.get("spark", [])),
        )
