# Code generated by contracts/codegen.py. DO NOT EDIT.
"""Generated Silver-layer models (LLM analysis)."""

from __future__ import annotations

from dataclasses import dataclass, field

from econ_core.models.enums import AnalysisStatus, Sentiment


@dataclass(kw_only=True)
class Analysis:
    """Silver record — LLM analysis of one Bronze news item (PRD analysis, AC2.1-AC2.6)."""

    record_id: str
    source_url: str
    target_countries: list[str] = field(default_factory=list)
    narrative_subjects: list[str] = field(default_factory=list)
    sentiment: Sentiment | None = None
    analysis_status: AnalysisStatus
    confidence: float
    analyzed_at: str
    analyzer_version: str

    @classmethod
    def from_dict(cls, d: dict) -> Analysis:
        return cls(
            record_id=d["record_id"],
            source_url=d["source_url"],
            target_countries=list(d.get("target_countries", [])),
            narrative_subjects=list(d.get("narrative_subjects", [])),
            sentiment=d.get("sentiment"),
            analysis_status=d["analysis_status"],
            confidence=d["confidence"],
            analyzed_at=d["analyzed_at"],
            analyzer_version=d["analyzer_version"],
        )
