#!/usr/bin/env python3
"""Schema-first code generator for the economic-opinion-trend-monitor contracts.

Standard library only, so ``make gen`` works before any dependency is installed.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
PY_OUT = ROOT / "python" / "packages" / "core" / "src" / "econ_core" / "models"
GO_OUT = ROOT / "go" / "gen"

HEADER = "// Code generated by contracts/codegen.py. DO NOT EDIT."
PY_HEADER = "# Code generated by contracts/codegen.py. DO NOT EDIT."

SCALARS_AVRO = {
    "string": ("str", "string"),
    "int": ("int", "int64"),
    "long": ("int", "int64"),
    "float": ("float", "float64"),
    "double": ("float", "float64"),
    "boolean": ("bool", "bool"),
}
SCALARS_JSON = {
    "string": ("str", "string"),
    "integer": ("int", "int64"),
    "number": ("float", "float64"),
    "boolean": ("bool", "bool"),
}
GO_INITIALISMS = {"id": "ID", "url": "URL"}


@dataclass
class Field:
    name: str
    kind: dict


@dataclass
class Record:
    name: str
    layer: str
    doc: str
    fields: list[Field] = field(default_factory=list)


ENUMS: dict[str, list[str]] = {}
RECORDS: dict[str, Record] = {}


def register_enum(name: str, symbols: list[str]) -> None:
    existing = ENUMS.get(name)
    if existing is not None and existing != symbols:
        raise SystemExit(f"enum '{name}' redefined with different symbols: {existing} vs {symbols}")
    ENUMS[name] = list(symbols)


def register_record(rec: Record) -> None:
    if rec.name in RECORDS:
        return
    RECORDS[rec.name] = rec


def resolve_avro(t, layer: str) -> dict:
    if isinstance(t, str):
        if t in SCALARS_AVRO:
            py, go = SCALARS_AVRO[t]
            return {"k": "scalar", "py": py, "go": go}
        if t in ENUMS:
            return {"k": "enum", "name": t}
        if t in RECORDS:
            return {"k": "record", "name": t}
        raise SystemExit(f"unknown Avro type reference: {t!r}")
    if isinstance(t, list):
        non_null = [x for x in t if x != "null"]
        if "null" not in t or len(non_null) != 1:
            raise SystemExit(f"unsupported Avro union (only ['null', X]): {t!r}")
        return {"k": "optional", "inner": resolve_avro(non_null[0], layer)}
    if isinstance(t, dict):
        tt = t["type"]
        if tt == "array":
            return {"k": "array", "items": resolve_avro(t["items"], layer)}
        if tt == "enum":
            register_enum(t["name"], t["symbols"])
            return {"k": "enum", "name": t["name"]}
        if tt == "record":
            parse_avro_record(t, layer)
            return {"k": "record", "name": t["name"]}
        return resolve_avro(tt, layer)
    raise SystemExit(f"cannot resolve Avro type: {t!r}")


def parse_avro_record(node: dict, layer: str) -> Record:
    fields = [Field(f["name"], resolve_avro(f["type"], layer)) for f in node["fields"]]
    rec = Record(name=node["name"], layer=layer, doc=node.get("doc", ""), fields=fields)
    register_record(rec)
    return rec


def parse_avro_file(path: Path) -> None:
    node = json.loads(path.read_text())
    parse_avro_record(node, node.get("x-layer", "silver"))


def resolve_json(fdef: dict) -> dict:
    if "enum" in fdef:
        name = fdef.get("x-enum-name")
        if not name:
            raise SystemExit("JSON Schema enum requires 'x-enum-name'")
        register_enum(name, fdef["enum"])
        return {"k": "enum", "name": name}
    jtype = fdef["type"]
    if jtype == "array":
        return {"k": "array", "items": resolve_json(fdef["items"])}
    if jtype in SCALARS_JSON:
        py, go = SCALARS_JSON[jtype]
        return {"k": "scalar", "py": py, "go": go}
    raise SystemExit(f"unsupported JSON Schema type: {jtype!r}")


def parse_json_schema_file(path: Path) -> None:
    schema = json.loads(path.read_text())
    fields = [Field(n, resolve_json(d)) for n, d in schema["properties"].items()]
    register_record(
        Record(
            name=schema["title"],
            layer=schema.get("x-layer", "bronze"),
            doc=schema.get("description", ""),
            fields=fields,
        )
    )


def py_type(kind: dict) -> str:
    k = kind["k"]
    if k == "scalar":
        return kind["py"]
    if k in ("enum", "record"):
        return kind["name"]
    if k == "array":
        return f"list[{py_type(kind['items'])}]"
    if k == "optional":
        return f"{py_type(kind['inner'])} | None"
    raise AssertionError(kind)


def py_from_dict_expr(f: Field) -> str:
    kind = f.kind
    k = kind["k"]
    if k in ("scalar", "enum"):
        return f'd["{f.name}"]'
    if k == "record":
        return f'{kind["name"]}.from_dict(d["{f.name}"])'
    if k == "array":
        items = kind["items"]
        if items["k"] == "record":
            return f'[{items["name"]}.from_dict(x) for x in d.get("{f.name}", [])]'
        return f'list(d.get("{f.name}", []))'
    if k == "optional":
        inner = kind["inner"]
        if inner["k"] == "record":
            return f'{inner["name"]}.from_dict(d["{f.name}"]) if d.get("{f.name}") is not None else None'
        return f'd.get("{f.name}")'
    raise AssertionError(kind)


def py_field_decl(f: Field) -> str:
    t = py_type(f.kind)
    if f.kind["k"] == "optional":
        return f"    {f.name}: {t} = None"
    if f.kind["k"] == "array":
        return f"    {f.name}: {t} = field(default_factory=list)"
    return f"    {f.name}: {t}"


def emit_python_records(records: list[Record], module_doc: str) -> str:
    enum_names, needs_field = set(), False
    for rec in records:
        for f in rec.fields:
            _collect_py_imports(f.kind, enum_names)
            if f.kind["k"] == "array":
                needs_field = True

    lines = [PY_HEADER, f'"""{module_doc}"""', "", "from __future__ import annotations", ""]
    dc_import = "from dataclasses import dataclass, field" if needs_field else "from dataclasses import dataclass"
    lines.append(dc_import)
    if enum_names:
        names = ", ".join(sorted(enum_names))
        lines.append(f"from econ_core.models.enums import {names}")
    lines.append("")

    for rec in records:
        lines.append("")
        lines.append("@dataclass(kw_only=True)")
        lines.append(f"class {rec.name}:")
        if rec.doc:
            lines.append(f'    """{rec.doc}"""')
            lines.append("")
        for f in rec.fields:
            lines.append(py_field_decl(f))
        lines.append("")
        lines.append("    @classmethod")
        lines.append(f'    def from_dict(cls, d: dict) -> {rec.name}:')
        lines.append("        return cls(")
        for f in rec.fields:
            lines.append(f"            {f.name}={py_from_dict_expr(f)},")
        lines.append("        )")
    return "\n".join(lines) + "\n"


def _collect_py_imports(kind: dict, enum_names: set[str]) -> None:
    k = kind["k"]
    if k == "enum":
        enum_names.add(kind["name"])
    elif k == "array":
        _collect_py_imports(kind["items"], enum_names)
    elif k == "optional":
        _collect_py_imports(kind["inner"], enum_names)


def emit_python_enums() -> str:
    lines = [PY_HEADER, '"""Generated enum value sets shared across data-lake layers."""', ""]
    lines.append("from typing import Literal")
    lines.append("")
    for name in sorted(ENUMS):
        symbols = ENUMS[name]
        literal = ", ".join(f'"{s}"' for s in symbols)
        # Trailing comma only for a 1-tuple; otherwise keep it compact so
        # ruff's magic-trailing-comma rule does not explode it across lines.
        values = f"({literal},)" if len(symbols) == 1 else f"({literal})"
        lines.append("")
        lines.append(f"{name} = Literal[{literal}]")
        lines.append(f"{name.upper()}_VALUES: tuple[{name}, ...] = {values}")
    return "\n".join(lines) + "\n"


def emit_python_init() -> str:
    lines = [PY_HEADER, '"""Generated data-lake models. Regenerate with `make gen`."""', ""]
    exports: list[str] = []
    for name in sorted(ENUMS):
        exports.append(name)
        exports.append(f"{name.upper()}_VALUES")
    enum_import = ", ".join(sorted(set(exports)))
    lines.append(f"from econ_core.models.enums import {enum_import}")
    for layer in ("bronze", "silver", "gold"):
        recs = sorted((r.name for r in RECORDS.values() if r.layer == layer))
        if recs:
            lines.append(f"from econ_core.models.{layer} import {', '.join(recs)}")
            exports.extend(recs)
    lines.append("")
    all_list = ",\n".join(f'    "{n}"' for n in sorted(set(exports)))
    lines.append(f"__all__ = [\n{all_list},\n]")
    return "\n".join(lines) + "\n"


def go_ident(snake: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", snake)
    out = []
    for p in parts:
        if not p:
            continue
        out.append(GO_INITIALISMS.get(p.lower(), p[:1].upper() + p[1:]))
    return "".join(out)


def go_symbol(sym: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", sym)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def go_type(kind: dict) -> str:
    k = kind["k"]
    if k == "scalar":
        return kind["go"]
    if k in ("enum", "record"):
        return kind["name"]
    if k == "array":
        return f"[]{go_type(kind['items'])}"
    if k == "optional":
        return f"*{go_type(kind['inner'])}"
    raise AssertionError(kind)


def emit_go_enums() -> str:
    lines = [HEADER, "", "package gen", ""]
    for name in sorted(ENUMS):
        lines.append(f"type {name} string")
        lines.append("")
        lines.append("const (")
        for sym in ENUMS[name]:
            lines.append(f'\t{name}{go_symbol(sym)} {name} = "{sym}"')
        lines.append(")")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def emit_go_records(records: list[Record]) -> str:
    lines = [HEADER, "", "package gen", ""]
    for rec in records:
        if rec.doc:
            lines.append(f"// {rec.name} {rec.doc}")
        lines.append(f"type {rec.name} struct {{")
        for f in rec.fields:
            tag = f.name + (",omitempty" if f.kind["k"] == "optional" else "")
            lines.append(f'\t{go_ident(f.name)} {go_type(f.kind)} `json:"{tag}"`')
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> None:
    for path in sorted((CONTRACTS / "bronze").glob("*.schema.json")):
        parse_json_schema_file(path)
    for path in sorted((CONTRACTS / "silver").glob("*.avsc")):
        parse_avro_file(path)
    for path in sorted((CONTRACTS / "gold").glob("*.avsc")):
        parse_avro_file(path)

    PY_OUT.mkdir(parents=True, exist_ok=True)
    GO_OUT.mkdir(parents=True, exist_ok=True)

    (PY_OUT / "enums.py").write_text(emit_python_enums())
    layer_doc = {
        "bronze": "Generated Bronze-layer models (raw collected news).",
        "silver": "Generated Silver-layer models (LLM analysis).",
        "gold": "Generated Gold-layer models (normalized aggregation).",
    }
    for layer, doc in layer_doc.items():
        recs = sorted((r for r in RECORDS.values() if r.layer == layer), key=lambda r: r.name)
        (PY_OUT / f"{layer}.py").write_text(emit_python_records(recs, doc))
    (PY_OUT / "__init__.py").write_text(emit_python_init())

    (GO_OUT / "enums.go").write_text(emit_go_enums())
    for layer in ("bronze", "silver", "gold"):
        recs = sorted((r for r in RECORDS.values() if r.layer == layer), key=lambda r: r.name)
        (GO_OUT / f"{layer}.go").write_text(emit_go_records(recs))

    n_rec = len(RECORDS)
    n_enum = len(ENUMS)
    print(f"codegen: {n_rec} records, {n_enum} enums -> {PY_OUT.relative_to(ROOT)} and {GO_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
